sudo: false
language: node_js

node_js:
  - "node"

cache:
  directories:
    - node_modules

install:
  - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - travis_retry npm install -g npm@latest
  - node -v && npm -v
  - npm rebuild
  - travis_retry npm install
  - npm prune

script:
  - npm test
